OK, this is going a bit overboard now, too much code
I’m also getting this error now: Caused by:
android.database.CursorIndexOutOfBoundsException: Index 6 requested,
with a size of 6